name: HelperXD
version: ${project.version}
main: me.quartzwarrior.Listener
api-version: 1.16
authors: [ QuartzWarrior ]
description: HelperXD is a plugin that makes the server nice and safe.
commands:
  godmode:
    description: Become invincible.
    aliases:
      - invincible
  feed:
    description: Hungry no longer.